name: coin_analyzer
description: Cryptocurrency portfolio and market explorer.
version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  flutter_circular_chart_two: ^0.1.2
  url_launcher: ^6.0.9
  package_info: ^2.0.2
  flutter_inappwebview: ^5.3.2
  web_socket_channel: ^2.0.0
  intl: ^0.17.0
  local_database:
  auto_size_text:
  flutter_svg:
  syncfusion_flutter_charts:
  flutter_webview_plugin:
  http: ^0.13.3
  web3dart: ^2.1.4
  fluttertoast: ^8.0.7
  slide_to_confirm: ^0.0.7
  flutter_spinkit: ^5.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  pinput: ^1.2.0
  numeric_keyboard: ^1.1.0
  flutter_string_encryption: ^0.3.1
  hex: ^0.2.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  lottie: ^1.1.0

  #Firebase
  firebase_core: ^1.4.0
  cloud_firestore: ^2.3.0
  firebase_storage: ^10.0.1

  #  Image Loading
  cached_network_image: ^3.1.0
  permission_handler: ^8.1.4+1
  image_cropper: ^1.4.1
  image_picker: ^0.8.2
  file_picker: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/abi/
    - assets/lottie/
